modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved, DragN0007"
issueTrackerURL="https://discord.gg/jubppqCzXj"
[[mods]]
modId="deadlydinos"
version="${1.18.2-1.5-REBUILD}"
displayName="DragN's Deadly Dinos"
logoFile="ddd.png"
credits="EvangeliX, code helper. Dominic, bone item artist. Emi, bug tester. Neko, criticism. I owe you guys the world." #optional
authors="DragN0007"
description='''
Adds aggressive, prehistoric creatures to your world. Build a strong base to survive.
Welcome to the DDD Rebuild!
Our Mod(s) Server & Issues Forum: https://discord.gg/jubppqCzXj
'''
[[dependencies.deadlydinos]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.deadlydinos]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19.0)"
ordering="NONE"
side="BOTH"
[[dependencies.deadlydinos]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.57,)"
ordering="NONE"
side="BOTH"
